### PR TITLE
Mobile hamburger animation transaction

### PR DESCRIPTION
**Pull request by developerfred**
close:  #685

screencast: https://youtu.be/l_FwuDHth6g

### CODE REVIEW

**Comment by anthonymartin** [comment]
@developerfred the build is failing - can you take a look?

**Comment by anthonymartin** [comment]
you can see the error message here: https://app.netlify.com/sites/popcorndao/deploys/619e60ead671150008c39af5

**Comment by developerfred** [comment]
> you can see the error message here: [app.netlify.com/sites/popcorndao/deploys/619e60ead671150008c39af5](https://app.netlify.com/sites/popcorndao/deploys/619e60ead671150008c39af5)

I'll just create the type for open

**Comment by developerfred** [comment]
https://youtu.be/l_FwuDHth6g

**Comment by FanFanDAO** [comment]
Hi, I am not seeing the latest demo link. Can you point me to it
Screen Shot 2021-12-02 at 12 53 23 PM
?

**Comment by developerfred** [comment]
> Hi, I am not seeing the latest demo link. Can you point me to it Screen Shot 2021-12-02 at 12 53 23 PM ?

https://deploy-preview-721--popcorndao.netlify.app/

**Comment by FanFanDAO** [comment]
I still see the jerking of the white content menu at the vert end of the animation. Also the X is not right-aligned with the horizontal shot separators and the entire menu. Can you fix this?

**Comment by developerfred** [comment]
> Hi, I am not seeing the latest demo link. Can you point me to it Screen Shot 2021-12-02 at 12 53 23 PM ?

@FanFanDAO https://deploy-preview-721--popcorndao.netlify.app/ ✅

**Comment by developerfred** [comment]
@FanFanDAO update: https://deploy-preview-721--popcorndao.netlify.app/

**Comment by developerfred** [comment]
@FanFanDAO update: deploy-preview-721--popcorndao.netlify.app

**Review by mefuru — APPROVED** [review]

**Comment by mefuru** [comment]
LGTM!

**Comment by developerfred** [comment]
@anthonymartin any update?

**Comment by anthonymartin** [comment]
Bounty will be paid with next billing cycle, at the end of the month.
thanks!

**Pull request merged**
