### PR TITLE
add doc generator for contracts

### PR DESCRIPTION
**Pull request by Soptq**
Deliverables:
* Documentations missing reports.
* Contracts filtering.
* Template modification.
* Gitbook compatible
* Supporting `devdoc`, `userdoc`, `title`, `params`, `returns`, and custom NatSpec tags.

Usage:

```
cd packages/contracts
npm install # or yarn
npm run docify # or yarn run docify
```

Any suggestion or possible improvement would be appreciated!

### CODE REVIEW

**Comment by Soptq** [comment]
I am aware that there is already someone working on this bounty, so please consider his solution first.

**Comment by developerfred** [comment]
> I am aware that there is already someone working on this bounty, so please consider his solution first.

Thanks, my solution: https://github.com/popcorndao/workspace/pull/370

**Comment by anthonymartin** [comment]
@developerfred is your PR ready? it says it's a WIP

**Comment by anthonymartin** [comment]
@developerfred it looks like the PR you raised includes code from this PR. Both of you have put me in a difficult situation. Since this PR was used as a basis #370, I suggest I split the bounty evenly with both of you.

**Comment by Soptq** [comment]
> @developerfred it looks like the PR you raised includes code from this PR. Both of you have put me in a difficult situation. Since this PR was used as a basis for #370, I suggest I split the bounty evenly with both of you.

Actually I think we are both being inspired by this post: https://forum.openzeppelin.com/t/incorporating-solidity-docgen-into-your-project/1882

However, this post was posted like 2 years ago and there are some drawbacks of this implementation in 2021:

1. the author was using `solidity-docgen` 0.3.11, which is outdated and has no support for solidity 0.7 (which is required by contracts in this repo).
2. the author's implementation is not compatible with the latest `solidity-docgen` 0.5.x.
2. the author was using `solc` compiler from `truffle` package. However, this repo doesn't really needs `truffle`.
3. the author doesn't implement some of the requirements in this bounty, be it documentations missing reports or interface filtering.

You can try our PR separately to see if it really meets your requirements. For me, I had resolved all above-mentioned drawbacks in this PR. However, considering another person started to work ahead of me, I think I can accept no matter what the final result would be. Even if I am not awarded by bounty, I am still super happy to contribute to the open source community 😄

**Comment by Soptq** [comment]
Ehh I took a closer look at #370 and I am not sure if his PR really achieves the bounty requirements. It seems to me that it is a 'one-time' documentation, for example interfaces are excluded by hands and there is no documentation missing report. @anthonymartin Maybe his PR is not finished yet, I think.

**Comment by anthonymartin** [comment]
Since @developerfred 's PR still does not meet the requirements as you pointed out @Soptq , I'd like to suggest that the both of you share the bounty while the #371 PR is merged in lieu of #370 .

However, I'm having issues running the code.

1. the first issue is that  the command wasn't running because the project is inside a lerna workspace so the node_modules is installed in the root directory and not the local. I fixed this by updating docify.js with this: `const NODE_DIR     = path.resolve(__dirname, "../../../node_modules");`
2.  then after resolving the above and running the script I encountered the following:
```
    ^

Error:     Error: Solidity was unable to compile.
    /popcorn/workspace-clean-2/packages/contracts/c
    ontracts/BeneficiaryGovernance.sol:164:20: ParserError: Expected ',' but
    got identifier
        bytes calldata _applicationCid,
                       ^-------------^
     (And 14 other errors...)
```

I updated the `     "--solc-module="        + LOCAL_NODE_DIR + "/solc",` line to point to the local node_modules since that's where solc was located, but still afterwards I received the following error:

```
Error:     Error: Solidity was unable to compile. /Users/anthonymartin/htdocs/popcorn
    /workspace-clean-2/packages/contracts/contracts/UniswapV2Router02.sol:1:1:
     ParserError: Source file requires different compiler version (current
    compiler is 0.7.6+commit.7338295f.Emscripten.clang) - note that nightly
    builds are considered to be strictly less than the released version
    pragma solidity =0.6.6;
    ^---------------------^
     (And 1 other errors...)
```

Can you help figure out this last piece to get it to play nice within the lerna project? it's not advised to run `yarn` from the local packages directory - it should be called from the root directory

**Comment by Soptq** [comment]
@anthonymartin I see. I had updated PR to make `docify.js` compatible with lerna workspace. My commands:

```
yarn install # Fresh clone, at project root.
yarn lerna run --scope @popcorn/contracts docify # At project root as well
```

And it works fine.

**Comment by anthonymartin** [comment]
It looks like I'm not able to run it because locally I've merged the feature on the develop branch (as mentioned in the original ticket) - and there's a contract that requires 0.6.6 compiler:

```
Error:     Error: Solidity was unable to compile. /Users/anthonymartin/htdocs/popcorn
    /workspace-clean-2/packages/contracts/contracts/UniswapV2Router02.sol:1:1:
     ParserError: Source file requires different compiler version (current
    compiler is 0.7.6+commit.7338295f.Emscripten.clang) - note that nightly
    builds are considered to be strictly less than the released version
    pragma solidity =0.6.6;
    ^---------------------^
     (And 1 other errors...)
```

We don't need to generate the documentation for this particular contract so is there a way to ignore it so it doesn't get compiled?

**Comment by Soptq** [comment]
@anthonymartin Yes there is! Try to add the following line to `packages/contracts/docgen/exclude.txt`.

```
UniswapV2Router02.sol
```

Basically if you want to exclude any contract from documentation, you can add its path (relative to `packages/contracts/contracts/`) to `exclude.txt`.

**Comment by Soptq** [comment]
@anthonymartin The dev branch PR had been merged, can I close this PR? Also I am totally OK with bounty sharing.

**Pull request closed without merging**
