### PR TITLE
Fixing component types

### LINKED ISSUE #243: ensure all components use same type

### PR DESCRIPTION
**Pull request by the-emerald**
They all seem to be fine save for one. Let me know what other changes are needed. Closes #243

### CODE REVIEW

**Comment by anthonymartin** [comment]
@the-emerald they are mostly defined like this using JSX.Element: 
```
export default function BeneficiaryCard(
  beneficiary: BeneficiaryApplication,
): JSX.Element {
```

so that needs to change as per #243 - can you rebase using the `develop-beneficiary-governance` branch?

**Comment by the-emerald** [comment]
Sure thing. Let me rebase and push.

**Comment by the-emerald** [comment]
@anthonymartin before I commit to fixing the rest of the modules, can you please confirm that e9894a71 does what you want?

**Comment by anthonymartin** [comment]
@the-emerald yep! that's right

**Comment by the-emerald** [comment]
Alright. I shall begin work now.

**Comment by the-emerald** [comment]
@anthonymartin I have gone ahead and fixed all the components in packages/app/. What other folders need fixing?

**Review by anthonymartin — APPROVED** [review]

**Pull request merged**
