### PR TITLE
first section on mobile landing page can be longer than 1 screen size…

### PR DESCRIPTION
**Pull request by Amirjab21**
… for smaller phones

### CODE REVIEW

**Comment by anthonymartin** [comment]
It looks like there is too much space between the animation and the top header. Could you reduce the size without affecting other screens?
Screen Shot 2021-09-09 at 3 45 53 PM

**Comment by Amirjab21** [comment]
@anthonymartin fixed up - let me know if theres anything left

**Comment by anthonymartin** [comment]
it's been reported that only one of the cats is animated in the new version (the one spinning in a circle), while the rest of it is not animated anymore

**Comment by Amirjab21** [comment]
> it's been reported that only one of the cats is animated in the new version (the one spinning in a circle), while the rest of it is not animated anymore

What devices is this for? It doesn't seem to be an issue on the netlify preview or on my local machine

**Comment by anthonymartin** [comment]
the issue was reported on the same target device iPhone Pro iOS 14.7.1

**Comment by Amirjab21** [comment]
I can’t recreate the issue on iOS 14.7.1 on iPhone 11.

Are you sure this report was looking at netlify on this branch?

**Comment by anthonymartin** [comment]
I can confirm that there is no animation in the svg - I double checked with the reporter and can verify that there is no animation using browser stack

**Comment by Amirjab21** [comment]
Sweeeet - I'd love to help out more on any other issues :)

**Comment by anthonymartin** [comment]
To be clear, it is expected that there is an animation visible @Amirjab21 and currently the image at the top with the cats jumping in the pool of popcorn is not animated as it is on other devices

**Comment by Amirjab21** [comment]
Apologies for that, I think I understand what the reviewer meant now. Initially, the animation for the red and blue cats was finite so would end after about 10 seconds. I've changed it so that it works infinitely. Was this the issue?

**Comment by anthonymartin** [comment]
Ok the animation is working in this version on the target device/os, but the animation should not be infinite for all the cats. previously, only the somersaulting cat and the tail in the pool were animated in a loop. the other cats should not loop infinitely.

**Comment by anthonymartin** [comment]
@Amirjab21 - merging now. thank you!

**Review by anthonymartin — APPROVED** [review]

**Pull request merged**
