### PR TITLE
Cat Pool Animation

### PR DESCRIPTION
**Pull request by themailman05**
Cats in pool animated with CSS as per spec.

Video demo here ->[Link]( https://siasky.net/AADTEtivhZpx7xNhM7PBIoxHou3Ba5XaAr9c3fvC8MIGkQ/)

### CODE REVIEW

**Comment by anthonymartin** [comment]
There are a few issues with this:
1. the small side pool shouldn't have any animated elements
2. the blue cat is not like in the original svg - there's missing parts of the design
3. the light blue cat and red cat are missing collars
5. the reference implementation [here](https://jsfiddle.net/sivaganeshan/4ocjmk3z/1/show) is smoother and longer for some reason. the diving cat and the falling popcorn are more in sync in the reference. they restart at the same time for instance and the whole animation seems to go on for a much longer time.
6. the svg has been updated on `main` - that one svg be used now instead if possible
7. can you make the light blue cat also move slowly up and towards the left?

**Comment by anthonymartin** [comment]
tagging https://github.com/sivaganeshan in case he can lend a hand too, @themailman05

**Comment by sivaganeshan** [comment]
> tagging @sivaganeshan in case he can lend a hand too, @themailman05

Will work on it.

**Comment by sivaganeshan** [comment]
> There are a few issues with this:
> 
> 1. the small side pool shouldn't have any animated elements
> 2. the blue cat is not like in the original svg - there's missing parts of the design
> 3. the light blue cat and red cat are missing collars
> 4. the reference implementation [here](https://jsfiddle.net/sivaganeshan/4ocjmk3z/1/show) is smoother and longer for some reason. the diving cat and the falling popcorn are more in sync in the reference. they restart at the same time for instance and the whole animation seems to go on for a much longer time.
> 5. the svg has been updated on `main` - that one svg be used now instead if possible
> 6. can you make the light blue cat also move slowly up and towards the left?

Hi @anthonymartin , 

The above asks are completed in this ### [jsfiddle](https://jsfiddle.net/sivaganeshan/8wd3ab6q/19/show)### demo , Can you review the design. If its ok, will implement the same into the project.

1. the small side pool shouldn't have any animated elements - **DONE**
2. the blue cat is not like in the original svg - there's missing parts of the design - **DONE**
3. the light blue cat and red cat are missing collars - **DONE**
4. the reference implementation [here](https://jsfiddle.net/sivaganeshan/4ocjmk3z/1/show) is smoother and longer for some reason. the diving cat and the falling popcorn are more in sync in the reference. they restart at the same time for instance and the whole animation seems to go on for a much longer time.
5. the svg has been updated on `main` - that one svg be used now instead if possible - **DONE**
6. can you make the light blue cat also move slowly up and towards the left? - **DONE**

cc:@themailman05

**Comment by anthonymartin** [comment]
looks great. the other thing i notice is that the popcorn that is already inside the pool should not be animated. could you fix that too?

**Comment by sivaganeshan** [comment]
> looks great. the other thing i notice is that the popcorn that is already inside the pool should not be animated. could you fix that too?

resolved it: refer this [demo](https://jsfiddle.net/sivaganeshan/8wd3ab6q/22/show).

**Comment by anthonymartin** [comment]
It's looking good, but these issues I mentioned before are still present it seems like:
Screen Shot 2021-08-28 at 12 21 26 PM

Screen Shot 2021-08-28 at 12 21 22 PM

**Review by anthonymartin — APPROVED** [review]

**Review by anthonymartin — APPROVED** [review]

**Pull request merged**
