### PR TITLE
Mocks + Interfaces cleanup

### LINKED ISSUE #221: Replace MockYearn / MockCurve contracts
Replace MockYearn / MockCurve contracts with production deployed abis where they don't need to be mocked (e.g. in `lib/SetToken`) and where the mocks are being used in tests, they should be replaced with waffle mocks instead using the production abis

> Not sure I understand this—is this just a shortcut to get access to the contract interface? If so, we should probably split out interfaces for all these dependencies somewhere. I've been thinking it's time to move these inline interfaces out of the contracts anyways.

_Originally posted by @ecmendenhall in https://github.com/popcorndao/workspace/pull/211#discussion_r665521240_

### PR DESCRIPTION
**Pull request by ecmendenhall**
Closes #221 

I merged `feature/batch-hysi-interaction` here to pull in @RedVeil's work extracting interfaces.

- Replace simple mocks (Curve registry, Curve address provider, Yearn registry) with Waffle `deployMockContract` + ABI. 
- Note: it's not possible to use Waffle mocks for anything that we want to side effect. That leaves us with several remaining hand-rolled mocks for Curve pools, basic issuance module, and Yearn V2 vaults. I see two options here:
    1. Keep these as-is. Be careful about ensuring the interfaces match up with reality. Make sure anything that uses one of these mocks also has a mainnet fork test that invokes the "real" contract.
    2. Use fork tests everywhere, delete these mocks altogether, and use the "real" contract in all tests. We would no longer be able to easily manipulate Curve virtual price/Yearn price-per-share in tests.
- Extract, simplify, and double check interfaces
- Move all third-party contracts to `/lib/` (Uniswap router, WETH)
- Clean up imports across contracts
- Remove unused mocks

### CODE REVIEW

**Comment by RedVeil** [comment]
I really like the cleanup!
Just renamed Interfaces/Integrations to interfaces/integrations for consistency (dunno why i had the capitalized before).

About your note:
I think i'd prefer option 2 and use the "real" implementations but create functions that simulate the behavior we want to test. (buy all tokens on one side of a curve pool / put X amount of money into a yearnVault) We could create a new folder for helper functions to deploy contracts, batch openVaults and manipulate integration contracts.

**Review by RedVeil — APPROVED** [review]

**Comment by anthonymartin** [comment]
This looks good. nice cleanup

>Use fork tests everywhere, delete these mocks altogether, and use the "real" contract in all tests. We would no longer be able to easily manipulate Curve virtual price/Yearn price-per-share in tests.

 I can imagine fork tests becoming a challenge if we ever need to change the fork block number right? Or would there be an easy way to set that per test @ecmendenhall

**Review by anthonymartin — APPROVED** [review]

**Comment by anthonymartin** [comment]
@ecmendenhall there are some conflicts here - could your review them?

**Comment by ecmendenhall** [comment]
@anthonymartin Yes, I'll give this an update today

**Pull request merged**
