### PR TITLE
Animated Rocket component added with webpack svgr loader

### PR DESCRIPTION
**Pull request by johnmgrimm**
Rocket component added in response to https://github.com/popcorndao/workspace/issues/376
SVGR webpack loader added to ease out loading SVGs to React (https://www.npmjs.com/package/@svgr/webpack).

### CODE REVIEW

**Comment by anthonymartin** [comment]
the idea for the spaceship is that it would shake/rumble and currently it looks like it's moving forward a little bit. It should shake left to right on the vertical axis of the spaceship. 

The stars and planets don't seem to be moving in all axes. For instance, when wobbling, they should be somewhat pinched to look like they are moving forward and backwards (moving forward and backwards skews the perspective).

**Comment by johnmgrimm** [comment]
Thanks for the feedback @anthonymartin,
I've added significantly more wobble to the movement of all animated objects and followed your advise regarding the rocket itself. Please review and let me know how do you like it now.

**Comment by anthonymartin** [comment]
Thanks for the revisions. I think what's best is the following:

remove animation on the spaceship altogether.
use the wobble animation from the previous iteration and perhaps slow it down. right now it looks too chaotic.

**Comment by johnmgrimm** [comment]
Hi, this is not exactly what you have asked for, but please take a look. I have slowed down all animations to make them less chaotic as you have requested.
For future feedback please tell me:
- how do you like the star "blinking" animation (I may apply same wobbling as for planets but I thought that it may be a bit better if not everything will wobble)
- what do you think about the current spaceship animation - IMHO it is not too violent but still looks a bit like it is traveling
- how about planets wobbling after slowing that down

**Comment by anthonymartin** [comment]
this looks better. can you slow down the spaceship even more ?

**Comment by johnmgrimm** [comment]
I've slowed down spaceship animation by 50%. Please let me know if you would like to adjust anything else.

**Comment by johnmgrimm** [comment]
Hi @anthonymartin, Please let me know if the animation is ok for you. If so maybe we can merge it?

**Comment by anthonymartin** [comment]
Yes, that's great! We are getting a new version of that image as the stroke was too thick. Would it be a problem updating the svg chop with the new version?

**Comment by johnmgrimm** [comment]
Not at all, I have it in the editable version. Just please let me know the diff.

**Comment by anthonymartin** [comment]
ok I'm waiting on the creative and will get it to you asap

**Comment by anthonymartin** [comment]
the new svg is in the main branch now @johnmgrimm

**Comment by johnmgrimm** [comment]
@anthonymartin it is done. I must admit that those thiner lines are looking better.
Please note that right now instead of **packages/app/public/images/rocket.svg** the application uses **packages/ui/src/components/Rocket/rocket.svg**
I didn't delete the old image in my PR as I'm not sure if you are not using it anywhere else.

**Comment by anthonymartin** [comment]
Looks great! Thank you!

**Pull request merged**
