### PR TITLE
Add popcorn etherscan link

### PR DESCRIPTION
**Pull request by Stanley-Okwii**
## Description

This PR adds the popcorn etherscan link to the main page

## Screenshot
Screen Shot 2021-09-03 at 12 14 54 AM

### CODE REVIEW

**Comment by anthonymartin** [comment]
@Stanley-Okwii could you set the target="_window" on these links?

**Comment by Stanley-Okwii** [comment]
> @Stanley-Okwii could you set the target="_window" on these links?

@anthonymartin, I have updated it accordingly.

**Comment by anthonymartin** [comment]
@Stanley-Okwii there are conflicts so the PR can't be merged. Can you fix those?

**Comment by Stanley-Okwii** [comment]
> @Stanley-Okwii there are conflicts so the PR can't be merged. Can you fix those?

Done ✅

**Review by anthonymartin — APPROVED** [review]

**Pull request merged**
