### PR TITLE
Add support for Solidity coverage

### LINKED ISSUE #364: add support for solidity coverage
_Branch_: `develop`

**Background**

We are using hardhat/mocha for running solidity tests in `packages/contracts`. Currently it is not possible to view the test coverage for the solidity contracts, so we would like to implement a tool like `solidity-coverage` to include in the CI/CD flow.

I tried installing `solidity-coverage` and running `yarn hardhat coverage` from `packages/contracts` but the following error occurs:
```
Compiling 58 files with 0.7.3
CompilerError: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack.

Error in plugin solidity-coverage: HardhatError: HH600: Compilation failed
```
So it is necessary to figure out what is causing the compilation error here and fix it, OR try implementing another library to produce test coverage reports.

**Acceptance Criteria**

* running a command like `yarn hardhat coverage` should successfully provide a test coverage report of our solidity contracts in `packages/contracts/contracts`
* mock contracts and vendor contracts (e.g. UniswapV2.sol, RandomNumberConsumer.sol) can be ignored and do not need to be included in coverage report
* The coverage command should be executed as a step in the `.github/workflows/run-tests.yml` file and visible on github PRs

### PR DESCRIPTION
**Pull request by leetdev**
Closes #364.

The issue turned out to be that the solidity-coverage plugin disables all optimizations when compiling contracts, but this causes the stack depth error when too many local variables are used somewhere in the code. There is currently an open issue to fix this at https://github.com/sc-forks/solidity-coverage/issues/636 - but since it's not implemented yet in the main repository, an alternative had to be used.

Turns out that someone created a fork of the plugin, where he implemented those changes (https://www.npmjs.com/package/@float-capital/solidity-coverage). Using that version I was able to get code coverage to work. So it is probably a good idea to keep an eye on the original plugin and change it back whenever a fixed version is released. I can try to do that for you, but will just in case leave the instructions here. Basically, all that needs to be done is remove the package `@float-capital/solidity-coverage`, install the original (`solidity-coverage`), and remove the `@float-capital/` vendor prefix in `hardhat.config.ts`.

I wasn't sure which contracts to skip, so I just added mocks and the 2 vendor contracts mentioned in the related issue. Feel free to add to the list as needed (the config is in `.solcover.js`).

### CODE REVIEW

**Comment by anthonymartin** [comment]
@leetdev are you able to isolate which contract is causing the issue? It would be preferable to use the main package instead of the forked on

**Comment by leetdev** [comment]
@anthonymartin I can try, but at the moment I'm not sure how to best figure it out. Let me see what I can do.

**Comment by anthonymartin** [comment]
That's great, we can create a ticket to refactor that function and close out this issue then. Thank you!

**Review by anthonymartin — APPROVED** [review]

**Comment by leetdev** [comment]
Happy to help!

**Comment by anthonymartin** [comment]
fixes #364

**Pull request merged**
